data<- read.table ("household_power_consumption.txt", header = TRUE, nrows=2075260, sep = ";", na.strings = "?")
data<- subset(data, data$Date %in% c("1/2/2007","2/2/2007"))
data$DateTime<- strptime(paste(data$Date,data$Time), format = "%d/%m/%Y %H:%M:%S" )
data<- na.omit(data)
Sys.setlocale("LC_TIME", "English")
data$DateTime<-as.POSIXct(data$DateTime)

dev.copy(png,'plot3.png', width = 480, height = 480)
plot( data$DateTime, data$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab =NA)
lines(data$DateTime, data$Sub_metering_2, col = "red")
lines(data$DateTime, data$Sub_metering_3, col = "blue")
legend("topright",  lty=1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()